### ISSUE TITLE
Sortable columns

### ISSUE THREAD

**Issue by lbatteau** [Opstandingskerk/NWonline#3]

**Comment by jeroenbaas** [comment]
I'm planning on integrating the jQuery plugin "datatables" to take care of this. Will also allow us to no longer need AJAX calls for filtering etc (everything happens @ user agent) http://www.datatables.net/

**Comment by lbatteau** [comment]
This does mean that the user always has the entire dataset locally... do we want that?

**Comment by lbatteau** [comment]
Then again, we load everything on start up, so it doesn't change anything really. I would say try it out!

**Comment by jeroenbaas** [comment]
yup. and I don't think we're looking at that much data all in all. i've been playing a bit with the datatables for a project at work and it looks really promising for our purpose. But I will do some proper testing (in all browser this time) of course.

**Comment by jeroenbaas** [comment]
ok, I've implemented datatables. I'm not happy with the loading time although that is not a datatables issue; it seems that my local server is quite slow if I output the entire table (loads the page for seconds). With datatables disables and just outputing the entire leden list the result is the same (long load time)
