### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by ruurdadema** [Opstandingskerk/NWonline#5]
Wat is de gedachte achter de verschillende branches?

Is bijvoorbeeld branch production ook echt de productie omgeving? Wordt die ge-update met een hook?

**Comment by jeroenbaas** [comment]
ik neem aan dat er geen automatische pull op de server uit die branch gebeurt, maar dat dit gewoon is om ervoor te zorgen dat er ontwikkeld kan worden in een development branch zonder dat je ontwikkelingen moet terugrollen als je een release wil doen zonder die nieuwste snufjes. Dus uiteindelijk ontwikkel je in de development branch en moet lukas dat denk ik naar de production pushen, en vervolgens in de gehoste omgeving een pull doen.

**Comment by ruurdadema** [comment]
De werking van verschillende branches en productie update is duidelijk, maar was even benieuwd naar de manier van werken.
Wat uiteindelijk natuurlijk niet uitmaakt in het kader van pull requests.
